fix: handle inflow and outflow with 0
nielsmaerten/ynab-buddy pull request #295
Opened 2024-07-01 18:40 UTC by tobim-dev

Hello Niels, I have found another bug. Sometimes my bank only has entries with 0 in the account statement. As a result, both the inflow and outflow columns have a value of 0.

If both columns contain a value of 0, the calculated amount is undefined and the upload to YNAB therefore fails. This PR fixes this behavior. The amount value shall be 0.

2024-07-15 11:21 UTC, nielsmaerten commented
Hi Tobias, thanks for the PR!  
Haven't had the time to test it yet, but hopefully by the end of next week.

In the meantime; I'm wondering: when does your bank create transactions like these?  
It's not something I've observed before, so this case may be unique to your bank.

I'd like to be certain YNAB correctly handles these zero-amount transactions because technically, no transfer of money has actually taken place. Depending on how YNAB handles them, it might be another option to discard them altogether before we submit to YNAB's API.

Greets,
Niels

2024-07-15 11:28 UTC, nielsmaerten requested changes
- [ ] There's a linting error blocking the merge
- [ ] Depending on how YNAB handles zero-transactions, maybe we can filter them out before submitting. To be discussed.

2024-07-15 11:28 UTC, nielsmaerten commented on src/lib/parser.spec.ts
> +  inflowOutflow0 = 12
PS: If you run `yarn lint:fix`, it will fix this linting error. Then the tests will pass and this PR can be merged.

2024-08-04 12:43 UTC, tobim-dev reviewed
Hi Niels, 

Apologies for the late reply. I agree with your point that it would be better to filter out those transactions before submitting them to YNAB. In YNAB, these would appear as transactions with neither inflow nor outflow. Several of my banks are doing this. These are bill transactions for using the banking service. Although some banks provide their account services technically for free, they still need to formally record a transaction indicating they are charging for their service, even if the amount is zero. However, this might just be a peculiarity of German bureaucracy.

I'll propose another solution filter out the transaction alltogether.

2024-08-09 14:10 UTC, merged

2024-08-09 14:23 UTC, nielsmaerten commented
Looks good to me! :) Merged ✅